In [12]:
## creating array 
import numpy as np 
arr1=np.array([1,2,3,4]) #1D array
print(arr)
arr2=np.array([[1],[2],[3],[4]])
print(arr2)
arr3=np.array([[1, 2], [3, 4]]) 
print(arr3)
#minimum dimension
arr4=np.array([1,2,3,4,5],ndmin=2)
print(arr4)
#dtype
arr5=np.array([2,3,4],dtype=complex)
print(arr5)

[1 2 3 4]
[[1]
 [2]
 [3]
 [4]]
[[1 2]
 [3 4]]
[[1 2 3 4 5]]
[2.+0.j 3.+0.j 4.+0.j]


In [14]:
#getting all functions in numpy
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_arg',
 '

In [16]:
# 3 D array
import numpy as np

arr6 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr6)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [17]:
#Checking no of dimensions
import numpy as np
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [11]:
# Creating Data Types in numpy
import numpy as np
a=np.dtype(np.int32) #int8,16,32,64 are called "i1","i2","i4","i6"etc
print(a)
b=np.dtype("i1") #int8
print(b)
c=np.dtype("i2") #int16
print(c)
d=np.dtype("i4") #int32
print(d)
e=np.dtype("i8") #int64
print(e)

int32
int8
int16
int32
int64


In [25]:
#creating structured data type
import numpy as np 
dt = np.dtype([("age",np.int8)])
arrw=np.array([10,20,30],dtype=dt)
print(arrw)
#student data type
student=np.dtype([("name","S20"),("age","i1"),("marks","f4")])
print(student)
s1=np.array([("Kruika",23,75.6),("Tohan",23,78.9)],dtype=student)
print(s1["name"])
print(s1["age"])
print(s1["marks"])


[(10,) (20,) (30,)]
[('name', 'S20'), ('age', 'i1'), ('marks', '<f4')]
[b'Kruika' b'Tohan']
[23 23]
[75.6 78.9]


In [36]:
#Numpy attributes
import numpy as np
a = np.array([[1,2,3],[4,5,6]]) 
print(a.shape)
#resizing array
a.shape=(3,2)
print(a)
#using reshape function
a1=np.array([[7,8,9],[10,11,12]])
b=a1.reshape(3,2)
print(b)
#creating 2D,3D array from 1D
a2=np.arange(12)
a2d=a2.reshape(4,3)
a3d=a2.reshape(2,2,3) 
print(a2d)
print(a3d)
print(a2.itemsize) #size of each element in array
a4=np.array([[1,2,3],[4,5,6]],dtype="i8")
print(a4.itemsize)
print(a4.flags)

(2, 3)
[[1 2]
 [3 4]
 [5 6]]
[[ 7  8]
 [ 9 10]
 [11 12]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
4
8
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False


In [60]:
import numpy as np
a1=np.empty((2,3),dtype=np.int8) #shape,dtype
print(a1)
a2=np.zeros((2,3),dtype=float) #shape,dtype
print(a2)
a3=np.zeros((2,2),dtype=[("x",int),("y",float)])#shape,dtype
print(a3)
print(a3["x"])
a4=np.ones((2,2)) #shape,dtype
print(a4)
#creating array from existing array
a=[1,2,3,4,5] #from list
a5=np.asarray(a,dtype=int) #array,dtype
print(a5)
a7=[(1,2,5),(6,7)] #from list of tuples
a5=np.asarray(a7)
print(a5)
s = 'Hello World' 
a8 = np.frombuffer(s, dtype = 'S1') #Not working
print(a8)

[[0 0 0]
 [0 0 0]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[(0, 0.) (0, 0.)]
 [(0, 0.) (0, 0.)]]
[[0 0]
 [0 0]]
[[1. 1.]
 [1. 1.]]
[1 2 3 4 5]
[(1, 2, 5) (6, 7)]


AttributeError: 'str' object has no attribute '__buffer__'

In [62]:
#using iterator to create ndarray
import numpy as np 
list = range(5) 
it = iter(list)  
# use iterator to create ndarray 
x = np.fromiter(it, dtype = float) #iterator,dtype
print(x)

[0. 1. 2. 3. 4.]


In [69]:
#Array from numerical ranges
import numpy as np
a=np.arange(5,10,1,dtype=float) #start,stop,step,dtype
print(a)
b=np.linspace(10,20,5,dtype=float)
print(b)
x = np.linspace(1,2,5, retstep = True) #start,stop,num,endpoint,retstep,dtype
print(x)
lo=np.logspace(1,5,num=10,base=2) #start,stop,num,endpoint,base,dtype
print(lo)

[5. 6. 7. 8. 9.]
[10.  12.5 15.  17.5 20. ]
(array([1.  , 1.25, 1.5 , 1.75, 2.  ]), 0.25)
[ 2.          2.72158     3.70349885  5.0396842   6.85795186  9.33223232
 12.69920842 17.28095582 23.51575188 32.        ]


In [76]:
#Accessing Array elements
a=np.arange(10)       #1D array
print(a)
s=slice(1,5,1)
print(a[s])
print(a[2:7:2])
print(a[5])
print(a[2:])
print(a[2:5])

[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4]
[2 4 6]
5
[2 3 4 5 6 7 8 9]
[2 3 4]


In [88]:
# Accessing Multidimensional Arrays
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 
print(a)
print(a[1:])#Slices 1st row away
print(a[...,1])#gives 2nd column
print(a[1,...])#gives 2nd row
print(a[...,1:])#gives everything from 1st column onwards

[[1 2 3]
 [3 4 5]
 [4 5 6]]
[[3 4 5]
 [4 5 6]]
[2 4 5]
[3 4 5]
[[2 3]
 [4 5]
 [5 6]]


In [94]:
#Advanced Indexing for multidimensional array
x = np.array([[1, 2], [3, 4], [5, 6]]) 
print(x)
y = x[[0,1,2], [0,1,0]] #gives(0,0),(1,1)and(2,0)position elements
print(y)
z = np.array([[ 0,  1,  2],[ 3,  4,  5],[ 6,  7,  8],[ 9, 10, 11]]) 
a=z[[0,1,2,3],[0,1,1,2]]# gives (0,0)(1,1)(2,1)and(3,2) position elements
print(a)
sli= z[1:4,1:3] #slices row from 1 to 3 and column 1 to 2
print(sli)

[[1 2]
 [3 4]
 [5 6]]
[1 4 5]
[ 0  4  7 11]
[[ 4  5]
 [ 7  8]
 [10 11]]


In [97]:
#More Advanced Indexing
z = np.array([[ 0,  1,  2],[ 3,  4,  5],[ 6,  7,  8],[ 9, 10, 11]]) 
rows = np.array([[0,0],[3,3]])
cols = np.array([[0,2],[0,2]]) 
print(rows)
print(cols)
y = z[rows,cols] #gives the elements(0,0),(0,2),(3,0),(3,2)
print(y)
k = z[1:4,[1,2]] 
print(k)

[[0 0]
 [3 3]]
[[0 2]
 [0 2]]
[[ 0  2]
 [ 9 11]]
[[ 4  5]
 [ 7  8]
 [10 11]]


In [7]:
#Boolean Indexing -used for comparison
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a[a<8]) #gives elements>8
b=np.array([np.nan,1,2,3,np.nan,5]) #removes null elements
print(b[~np.isnan(b)])
c=np.array([1,1+2j,3+3j,3]) #removes complex elements
print(c[~np.iscomplex(c)])

[1 2 3 4 5 6 7]
[1. 2. 3. 5.]
[1.+0.j 3.+0.j]


In [14]:
#Broadcasting in numpy-used to treat arrays of different shapes while mathematical operations
a=np.array([1,2,3,4])
b=np.array([10,20,30,40])
print(a*b)
c=np.array([10,20,30])
print(b*c) #Not possible because of index mismatch

[ 10  40  90 160]


ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [13]:
#Addition with broadcasting
import numpy as np 
a = np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]]) 
b = np.array([1.0,2.0,3.0])  
   
print('First array:')
print(a)
print('\n')  
   
print('Second array:') 
print(b) 
print('\n')  
   
print('First Array + Second Array') 
print(a + b)

First array:
[[ 0.  0.  0.]
 [10. 10. 10.]
 [20. 20. 20.]
 [30. 30. 30.]]


Second array:
[1. 2. 3.]


First Array + Second Array
[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]


In [21]:
#iteration over arrays-using nditer
a=np.array([1,2,3,4,5])
for x in np.nditer(a):
    print(x)
b=np.arange(5,50,5)
print(b)
c=b.reshape(3,3)
print(c)
for y in np.nditer(c):
    print(y)

1
2
3
4
5
[ 5 10 15 20 25 30 35 40 45]
[[ 5 10 15]
 [20 25 30]
 [35 40 45]]
5
10
15
20
25
30
35
40
45


In [30]:
# Transpose of a matrix
a=np.array([[1,2,3],[4,5,6]])
print(a)
print(a.T) #transpose
#iterating row wise
c=a.copy(order="F")
print(c)
for x in np.nditer(c): #iteration column wise
    print(x)
d=a.copy(order="C")
print(d)
for x in np.nditer(d): #iteration row wise
    print(x)
print("Modified array")
for x in np.nditer(d,op_flags=["readwrite"]):
    x[...]=2*x
    print(x)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[[1 2 3]
 [4 5 6]]
1
4
2
5
3
6
[[1 2 3]
 [4 5 6]]
1
2
3
4
5
6
Modified array
2
4
6
8
10
12


In [36]:
#Traversing each column using flags
print(d)
for x in np.nditer(d,flags=["external_loop"],order="F"):
    print(x)
for x in np.nditer(d,flags=["external_loop"],order="C"): #rowwise
    print(x)
#traversing two arrays together
a = np.arange(0,60,5) 
a = a.reshape(3,4) 

print ('First array is:') 
print (a) 
print ('\n')  

print ('Second array is:')
b = np.array([1, 2, 3, 4], dtype = int) 
print (b) 
print ('\n') 

print ('Modified array is:')
for x,y in np.nditer([a,b]): 
   print("%d:%d" % (x,y))

[[ 2  4  6]
 [ 8 10 12]]
[2 8]
[ 4 10]
[ 6 12]
[ 2  4  6  8 10 12]
First array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


Second array is:
[1 2 3 4]


Modified array is:
0:1
5:2
10:3
15:4
20:1
25:2
30:3
35:4
40:1
45:2
50:3
55:4


In [59]:
#array manipulation functions
a=np.array([[1,2,3],[4,5,6]])
#changing shape of array
print(a.reshape((3,2)))
print(a.flat[5]) 
print(a.flatten(order="C"))
print(a.ravel(order="C"))
#taking transpose and axis change
print(np.transpose(a))
print(np.rollaxis(a,1))
print(a.T)
print(np.swapaxes(a,1,0))
#changing dimension
x = np.array([[1], [2], [3]]) 
y = np.array([4, 5, 6])  
b = np.broadcast(x,y)  
r,c = b.iters 
print(r.next(), c.next())
print(r.next(), c.next())
print('\n')  

[[1 2]
 [3 4]
 [5 6]]
6
[1 2 3 4 5 6]
[1 2 3 4 5 6]
[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]


AttributeError: 'numpy.flatiter' object has no attribute 'next'

In [75]:
#changing dimensions
a = np.arange(4).reshape(1,4)
print(a)
print(np.broadcast_to(a,(4,4))) #changes shape (array,shape of new array)
x = np.array(([1,2],[3,4])) 
y = np.expand_dims(x, axis = 2) #expanding dimensions around axis(array,axis)
print(y)
print(x)
print(x.shape)
print(y.shape)
b = np.arange(9).reshape(1,3,3) 
print(b)
z=np.squeeze(b) #removes single dimension from the shape
print(z)
print(b.shape)
print(z.shape)

[[0 1 2 3]]
[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]
[[[1]
  [2]]

 [[3]
  [4]]]
[[1 2]
 [3 4]]
(2, 2)
(2, 2, 1)
[[[0 1 2]
  [3 4 5]
  [6 7 8]]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
(1, 3, 3)
(3, 3)


In [97]:
#Joining Arrays
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
print(np.concatenate((a,b),axis=0)) #adding along existing axis [(arrays),axis]
print(np.stack((a,b),1))#adding along axis in new array  [(arrays),axis]
print(np.hstack((a,b)))#adding horizontally
print(np.vstack((a,b)))#adding vertically
#Splitting Arrays
a=np.arange(10)
print(a)
print(np.split(a,[3,7]))#splitting at particular position
print(np.hsplit(a,[5]))#splitting horizontally[array,position for splitting]
b=a.reshape(5,2)
print(b)
print(np.vsplit(b,[2]))#splitting vertically[array,position for splitting]

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]
[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[0 1 2 3 4 5 6 7 8 9]
[array([0, 1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])]
[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[array([[0, 1],
       [2, 3]]), array([[4, 5],
       [6, 7],
       [8, 9]])]


In [121]:
#Adding and Removing elements
a=np.array([1,2,3,4,5,6])
b=np.resize(a,(3,2))#[array,shape]
print(b)
print(np.append(b,[[7,8],[9,10]],0))
c=np.array([[1,2,3],[4,5,6]])
print(np.append(c,[[7,8,9],[10,11,12]],0)) #adding elements along axis 0[array,values,axis]
print(np.append(c,[[7,8,9],[10,11,12]],1)) #adding elements along axis 1
print(np.insert(c,2,[11,12],1))#inserting elements at particular index at particular axis[array,index,values,axis]

[[1 2]
 [3 4]
 [5 6]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
[[ 1  2 11  3]
 [ 4  5 12  6]]


In [128]:
#deleting a subarray
a = np.arange(12).reshape(3,4) 
print(a)
print(np.delete(a,2,0))#[array,index at which deletion takes place,axis along which]
print(np.delete(a,2,1))#1st axis
print(a.ndim)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[0 1 2 3]
 [4 5 6 7]]
[[ 0  1  3]
 [ 4  5  7]
 [ 8  9 11]]
2


In [129]:
a = np.array([5,2,6,2,7,5,6,8,2,9]) 
print(np.unique(a))#Also returns return_index,return_count and return_inverse]

[2 5 6 7 8 9]


In [140]:
#Bitwise Binary operators
a,b=13,17
print(bin(a),bin(b))
print(np.bitwise_and(13, 17))
print(np.bitwise_or(13, 17))
print(np.invert(1))
print(np.left_shift(1,2))
print(np.right_shift(178,3))

0b1101 0b10001
1
29
-2
4
22


In [173]:
#vectorized string operations
a=np.char.add("Hello ","World")
b=np.char.add(["My ","Name"],["Krutika ","Talegaonkar"])
c=np.char.multiply(["Hello  ","Krutika "],3)
d=np.char.split("My name is Krutika")
e=np.char.split('hello how are you?') 
f=np.char.splitlines("Hello\nLet's rock")
g=np.char.strip('ashok arora','a')
h=np.char.join(":","dmy")
i=np.char.join([":","-"],["fmy","ygh"])
j=np.char.replace("my name is Krutika","is","was")

print(e)
print(a)
print(b)
print(c)
print(d)
print(f)
print(g)
print(h)
print(i)
print(j)

['hello', 'how', 'are', 'you?']
Hello World
['My Krutika ' 'NameTalegaonkar']
['Hello  Hello  Hello  ' 'Krutika Krutika Krutika ']
['My', 'name', 'is', 'Krutika']
['Hello', "Let's rock"]
shok aror
d:m:y
['f:m:y' 'y-g-h']
my name was Krutika


In [174]:
#function for rounding off numbers
np.around(2.3456,2)

2.35

In [182]:
#Mathematical operations
a = np.arange(9, dtype = np.float_).reshape(3,3) 

print('First array:') 
print(a)  
b = np.array([10,10,10]) 
print( b ) 

print(np.add(a,b)) 
print (np.subtract(a,b)) 
print (np.multiply(a,b)) 
print (np.divide(a,b))
print(np.reciprocal(a))
print(np.power(a,2))

First array:
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
[10 10 10]
[[10. 11. 12.]
 [13. 14. 15.]
 [16. 17. 18.]]
[[-10.  -9.  -8.]
 [ -7.  -6.  -5.]
 [ -4.  -3.  -2.]]
[[ 0. 10. 20.]
 [30. 40. 50.]
 [60. 70. 80.]]
[[0.  0.1 0.2]
 [0.3 0.4 0.5]
 [0.6 0.7 0.8]]
[[       inf 1.         0.5       ]
 [0.33333333 0.25       0.2       ]
 [0.16666667 0.14285714 0.125     ]]
[[ 0.  1.  4.]
 [ 9. 16. 25.]
 [36. 49. 64.]]


C:\Users\KRUTER\Anaconda3\lib\site-packages\ipykernel_launcher.py:13: RuntimeWarning: divide by zero encountered in reciprocal
  del sys.path[0]


In [213]:
#statistical functions
a=np.array([[1,2,3],[4,5,6]])
print(np.amin(a))
print(np.amax(a))
print(np.amin(a,1))
print(np.amax(a,1))
print(np.amin(a,0)) #Gives min number along axis 0
print(np.amax(a,0))
print(np.ptp(a))
print(np.ptp(a,0)) #gives range along axis 0
print(np.ptp(a,1))
print(np.percentile(a,30))
print(np.percentile(a,30,axis=1))
print(np.percentile(a,30,axis=0))#(array,percentile,axis)
print(np.median(a))
print(np.median(a,1))
print(np.median(a,0))
print(np.mean(a))
print(np.mean(a,0))
print(np.mean(a,1)) #array,axis
print(np.average(a)) # calculates weighed average
print(np.average(a,weights=[[4,5,6],[7,8,9]]))# has argument for weighs after array
print(np.std(a))#standard deviation
print(np.var(a))#variance of the data

1
6
[1 4]
[3 6]
[1 2 3]
[4 5 6]
5
[3 3 3]
[2 2]
2.5
[1.6 4.6]
[1.9 2.9 3.9]
3.5
[2. 5.]
[2.5 3.5 4.5]
3.5
[2.5 3.5 4.5]
[2. 5.]
3.5
3.948717948717949
1.707825127659933
2.9166666666666665


In [220]:
#sorting of Arrays
a=np.array([[5,4],[3,8]])
print(np.sort(a))
print(np.sort(a,axis=0)) #array,axis,kind,order arguments 
print(np.sort(a,axis=1)) #order is field if the array contains fields
dt = np.dtype([('name', 'S10'),('age', int)]) 
b= np.array([("raju",21),("anil",25),("ravi", 17), ("amar",27)], dtype = dt) 
print(np.sort(b))
print(np.sort(b,axis=0,order="name"))


[[4 5]
 [3 8]]
[[3 4]
 [5 8]]
[[4 5]
 [3 8]]
[(b'amar', 27) (b'anil', 25) (b'raju', 21) (b'ravi', 17)]
[(b'amar', 27) (b'anil', 25) (b'raju', 21) (b'ravi', 17)]


In [233]:
#other sorting functions
x = np.array([3, 1, 2]) #indirect sort provides the indexes of the list in a sorted manner using which array can be
#reconstructed
y=np.argsort(x)
print(x[y]) #reconstructing original array
for i in y:
    print(x[i])
nm = ('raju','anil','ravi','amar') 
dv = ('f.y.', 's.y.', 's.y.', 'f.y.') 
k=np.lexsort((dv,nm)) #assessed using keys
print(k)
for i in k:
    print(nm[i])   
a=np.array([1,3,7,9,0])
print(a[np.argmax(a)]) #index of max element
print(a[np.argmin(a)]) #index of min element
print(np.nonzero(a)) #index of non zero elements
b=np.array([8,5,3,9])
i=np.where(b>8)      
print(b[i]) #to find index of subarray satisfying particular condition
print(np.extract(b>3,b)) #returns elements satisfying condition has 2 arguments-condition and array

[1 2 3]
1
2
3
[3 1 0 2]
amar
anil
raju
ravi
9
0
(array([0, 1, 2, 3], dtype=int64),)
[9]
[8 5 9]


In [246]:
#matrix library
import numpy.matlib
a=np.matlib.empty((2,3)) #shape,dtype,order
print(a)
b=np.matlib.zeros((3,3))
print(b)
c=np.matlib.ones((4,4))
print(c)
d=np.matlib.eye(2, 2,k=0, dtype=float) #no of rowa,no of columns,index of diagnonal element,dtype
print(d)
e=np.matlib.identity(5,dtype=float)# generates Identity matrix
print(e)
f=np.matlib.rand((3,3))
print(f)


[[1. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 0.]
 [0. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[0.26297893 0.08887324 0.42607755]
 [0.90154645 0.34791171 0.32397424]
 [0.32413211 0.93820461 0.9495472 ]]
